apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $appname-app
  namespace: default
spec:
  dnsNames:
    - $hostname
  secretName: $appname-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer